#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "PyYAML",
#     "xero-python",
# ]
# ///
"""
Xero Manual Journals Manager

This script allows you to view and manage your Xero Manual Journals via the API.

Usage:
    ./xero_journal_manager.py <command> [options]

Commands:
    view    List all manual journals in CSV format. Supports optional filtering query.
    edit    Edit a manual journal (e.g. change account code).

Examples:
    # View all manual journals
    ./xero_journal_manager.py view

    # View journals filtered by AccountCode
    ./xero_journal_manager.py view "AccountCode == '127'"

    # View journals filtered by Amount and Status
    ./xero_journal_manager.py view "LineAmount > 1000 and Status != 'VOIDED'"

    # View journals filtered by Date
    ./xero_journal_manager.py view "Date >= '2025-11-01'"

    # Edit a journal to change account code (Dry Run)
    ./xero_journal_manager.py edit --journal-id <ID> --find-account 265 --new-account 810 --dry-run

    # Edit a journal to change account code (Apply)
    ./xero_journal_manager.py edit --journal-id <ID> --find-account 265 --new-account 810

Requirements:
    - xero_config.yaml (with CLIENT_ID, CLIENT_SECRET)
    - .xero_token.json (generated by xero_connect.py)
"""
import argparse
import os
import json
import yaml
import csv
import sys
import signal
from xero_python.api_client import ApiClient
from xero_python.api_client.configuration import Configuration
from xero_python.api_client.oauth2 import OAuth2Token
from xero_python.identity import IdentityApi
from xero_python.accounting import AccountingApi, ManualJournals

# Handle broken pipe when piping output
signal.signal(signal.SIGPIPE, signal.SIG_DFL)


def load_config(config_file="xero_config.yaml"):
    with open(config_file, "r") as f:
        return yaml.safe_load(f)


def load_token(token_file=".xero_token.json"):
    if not os.path.exists(token_file):
        print("Token file not found. Please run xero_connect.py first.")
        return None
    with open(token_file, "r") as f:
        return json.load(f)


def list_journals(api_client, tenant_id, query=None):
    # 2. Get Manual Journals
    accounting_api = AccountingApi(api_client)

    all_journals = []
    page = 1

    # print("Fetching manual journals...", file=sys.stderr)

    while True:
        # print(f"Fetching page {page}...", file=sys.stderr)
        journals_response = accounting_api.get_manual_journals(tenant_id, page=page)

        if not journals_response.manual_journals:
            break

        all_journals.extend(journals_response.manual_journals)
        page += 1

    # print(f"Found {len(all_journals)} journals.", file=sys.stderr)

    # 3. Output to CSV
    writer = csv.writer(sys.stdout)
    # Header
    writer.writerow(
        [
            "JournalID",
            "Date",
            "Narration",
            "Status",
            "LineID",
            "AccountCode",
            "Description",
            "LineAmount",
            "TaxType",
        ]
    )

    for journal in all_journals:
        # We might need to fetch details if lines are not included in the list endpoint?
        # Xero API documentation says get_manual_journals returns ManualJournals which includes JournalLines.
        # Let's verify if lines are present.

        # If lines are missing, we might need to fetch each journal individually, but that would be slow.
        # Usually list endpoint returns lines for Manual Journals.

        if journal.journal_lines:
            for line in journal.journal_lines:
                row_data = {
                    "JournalID": journal.manual_journal_id,
                    "Date": str(journal.date),
                    "Narration": journal.narration,
                    "Status": journal.status,
                    "LineID": getattr(line, "line_item_id", ""),
                    "AccountCode": line.account_code,
                    "Description": line.description,
                    "LineAmount": line.line_amount,
                    "TaxType": line.tax_type,
                }

                if query:
                    try:
                        # Evaluate the query against the row data
                        if not eval(query, {}, row_data):
                            continue
                    except Exception as e:
                        print(
                            f"Error evaluating query '{query}' for row: {e}",
                            file=sys.stderr,
                        )
                        continue

                writer.writerow(
                    [
                        row_data["JournalID"],
                        row_data["Date"],
                        row_data["Narration"],
                        row_data["Status"],
                        row_data["LineID"],
                        row_data["AccountCode"],
                        row_data["Description"],
                        row_data["LineAmount"],
                        row_data["TaxType"],
                    ]
                )
        else:
            # Just write the journal info if no lines (shouldn't happen for valid journals)
            row_data = {
                "JournalID": journal.manual_journal_id,
                "Date": str(journal.date),
                "Narration": journal.narration,
                "Status": journal.status,
                "LineID": "",
                "AccountCode": "",
                "Description": "",
                "LineAmount": 0.0,
                "TaxType": "",
            }

            if query:
                try:
                    if not eval(query, {}, row_data):
                        continue
                except Exception:
                    continue

            writer.writerow(
                [
                    row_data["JournalID"],
                    row_data["Date"],
                    row_data["Narration"],
                    row_data["Status"],
                    "",
                    "",
                    "",
                    "",
                    "",
                ]
            )


def edit_journal(api_client, tenant_id, journal_id, find_account, new_account, dry_run=False):
    accounting_api = AccountingApi(api_client)

    try:
        # Get the journal
        print(f"Fetching journal {journal_id}...", file=sys.stderr)
        journal_response = accounting_api.get_manual_journal(tenant_id, journal_id)

        if not journal_response.manual_journals:
            print(f"Journal {journal_id} not found.", file=sys.stderr)
            return

        journal = journal_response.manual_journals[0]

        print(f"Found Journal: {journal.manual_journal_id} - {journal.narration}")

        updated = False
        if journal.journal_lines:
            for line in journal.journal_lines:
                if line.account_code == find_account:
                    print(
                        f"  - Found line matching AccountCode '{find_account}': {line.description} ({line.line_amount})"
                    )
                    print(f"    -> Changing AccountCode to '{new_account}'")
                    line.account_code = new_account
                    updated = True

        if not updated:
            print(f"No lines found with AccountCode '{find_account}'. No changes made.")
            return

        if dry_run:
            print("Dry run: Changes not applied.")
            return

        # Update the journal
        print("Applying changes...", file=sys.stderr)
        # We need to wrap the journal in a list for the update call
        # Note: Xero API might require specific fields or complain about read-only ones.
        # But usually passing the object back works for updates.

        accounting_api.update_manual_journal(
            tenant_id,
            journal_id,
            manual_journals=ManualJournals(manual_journals=[journal]),
        )
        print("Journal updated successfully.")

    except Exception as e:
        print(f"Error updating journal: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Manage Xero Manual Journals")
    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # View command
    view_parser = subparsers.add_parser("view", help="List all manual journals in CSV format")
    view_parser.add_argument("query", nargs="?", help="Filter query (e.g. \"AccountCode == '810'\")")

    # Edit command
    edit_parser = subparsers.add_parser("edit", help="Edit a manual journal")
    edit_parser.add_argument("--journal-id", required=True, help="The ID of the journal to edit")
    edit_parser.add_argument("--find-account", required=True, help="The account code to find")
    edit_parser.add_argument("--new-account", required=True, help="The new account code")
    edit_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Simulate the edit without applying changes",
    )

    args = parser.parse_args()

    config = load_config()
    token_data = load_token()

    if not token_data:
        return

    # Create the token object first
    oauth2_token = OAuth2Token(client_id=config["CLIENT_ID"], client_secret=config["CLIENT_SECRET"])
    oauth2_token.update_token(**token_data)

    api_client = ApiClient(
        Configuration(debug=False, oauth2_token=oauth2_token),
        pool_threads=1,
    )

    @api_client.oauth2_token_getter
    def obtain_xero_oauth2_token():
        return token_data

    @api_client.oauth2_token_saver
    def store_xero_oauth2_token(token):
        nonlocal token_data
        token_data = token
        with open(".xero_token.json", "w") as f:
            json.dump(token, f, indent=4)

    # Refresh token
    try:
        api_client.refresh_oauth2_token()
    except Exception as e:
        print(f"Warning: Token refresh failed: {e}", file=sys.stderr)

    # 1. Get Tenant ID
    identity_api = IdentityApi(api_client)
    connections = identity_api.get_connections()

    if not connections:
        print("No connections found.")
        return

    tenant_id = connections[0].tenant_id

    if args.command == "view":
        list_journals(api_client, tenant_id, args.query)
    elif args.command == "edit":
        edit_journal(
            api_client,
            tenant_id,
            args.journal_id,
            args.find_account,
            args.new_account,
            args.dry_run,
        )
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
