#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "PyYAML",
#     "xero-python",
# ]
# ///
"""
Xero Chart of Accounts Manager

This script allows you to view and manage your Xero Chart of Accounts via the API.

Usage:
    ./xero_coa_manager.py <command> [options]

Commands:
    view    List all accounts in CSV format. Supports optional filtering query.
    add     Add a new account.

Examples:
    # View all accounts
    ./xero_coa_manager.py view

    # View accounts filtered by Code
    ./xero_coa_manager.py view "Code == '810'"

    # View accounts filtered by Type
    ./xero_coa_manager.py view "Type == 'CURRLIAB'"

    # Add a new liability account
    ./xero_coa_manager.py add --code 810 --name "Crypto Loan Principal" --type CURRLIAB --description "Liability account for tracking crypto loan principal balances" --tax-type NONE

    # Add a new expense account
    ./xero_coa_manager.py add --code 450 --name "Consulting Fees" --type EXPENSE

Requirements:
    - xero_config.yaml (with CLIENT_ID, CLIENT_SECRET)
    - .token.json (generated by xero_connect.py)
"""
import argparse
import csv
import sys
import os
import json
import yaml
import signal

# Handle broken pipe when piping output
signal.signal(signal.SIGPIPE, signal.SIG_DFL)

from xero_python.api_client import ApiClient
from xero_python.api_client.configuration import Configuration
from xero_python.api_client.oauth2 import OAuth2Token
from xero_python.identity import IdentityApi
from xero_python.accounting import AccountingApi, Account, AccountType

def load_config(config_file='xero_config.yaml'):
    if not os.path.exists(config_file):
        print(f"Config file {config_file} not found.")
        sys.exit(1)
    with open(config_file, 'r') as f:
        return yaml.safe_load(f)

def load_token(token_file='.token.json'):
    if not os.path.exists(token_file):
        print("Token file not found. Please run xero_connect.py first.")
        sys.exit(1)
    with open(token_file, 'r') as f:
        return json.load(f)

def get_api_client():
    config = load_config()
    token_data = load_token()

    oauth2_token = OAuth2Token(
        client_id=config['CLIENT_ID'],
        client_secret=config['CLIENT_SECRET']
    )
    oauth2_token.update_token(**token_data)

    api_client = ApiClient(
        Configuration(
            debug=False,
            oauth2_token=oauth2_token
        ),
        pool_threads=1,
    )

    @api_client.oauth2_token_getter
    def obtain_xero_oauth2_token():
        return token_data

    @api_client.oauth2_token_saver
    def store_xero_oauth2_token(token):
        nonlocal token_data
        token_data = token
        with open('.token.json', 'w') as f:
            json.dump(token, f, indent=4)

    # Refresh token
    try:
        api_client.refresh_oauth2_token()
    except Exception as e:
        print(f"Warning: Token refresh failed: {e}")

    return api_client

def get_tenant_id(api_client):
    identity_api = IdentityApi(api_client)
    connections = identity_api.get_connections()
    if not connections:
        print("No Xero connections found.")
        sys.exit(1)
    return connections[0].tenant_id

def list_accounts(api_client, tenant_id, query=None):
    accounting_api = AccountingApi(api_client)
    try:
        accounts = accounting_api.get_accounts(tenant_id)

        writer = csv.writer(sys.stdout)
        writer.writerow(["Code", "Name", "Type", "TaxType", "Description", "Status", "AccountID"])

        # Sort by Code for better readability
        sorted_accounts = sorted(accounts.accounts, key=lambda x: x.code if x.code else "")

        for account in sorted_accounts:
            row_data = {
                "Code": account.code,
                "Name": account.name,
                "Type": str(account.type),
                "TaxType": account.tax_type,
                "Description": account.description,
                "Status": account.status,
                "AccountID": account.account_id
            }

            if query:
                try:
                    # Evaluate the query against the row data
                    if not eval(query, {}, row_data):
                        continue
                except Exception as e:
                    print(f"Error evaluating query '{query}' for row: {e}", file=sys.stderr)
                    continue

            writer.writerow([
                row_data["Code"],
                row_data["Name"],
                row_data["Type"],
                row_data["TaxType"],
                row_data["Description"],
                row_data["Status"],
                row_data["AccountID"]
            ])
    except Exception as e:
        print(f"Error fetching accounts: {e}", file=sys.stderr)
        sys.exit(1)

def add_account(api_client, tenant_id, code, name, account_type, description=None, tax_type=None):
    accounting_api = AccountingApi(api_client)

    try:
        # Handle case where account_type might be passed as string but needs to be Enum
        # Some versions of SDK might accept string, but this one seems strict
        if isinstance(account_type, str):
            # Try to match with AccountType enum
            # AccountType has members like CURRENT, REVENUE, etc.
            # Check if the string matches any member name
            if hasattr(AccountType, account_type):
                account_type = getattr(AccountType, account_type)
            else:
                # Fallback or error? Let's try to pass it as is if not found,
                # but the error said "Can't serialize value type 'str' to explicit type 'AccountType'"
                # So it MUST be an enum.
                print(f"Error: Invalid Account Type '{account_type}'.")
                print(f"Valid types: {[e.name for e in AccountType]}")
                sys.exit(1)

    except Exception as e:
        print(f"Error processing account type: {e}")
        sys.exit(1)

    new_account = Account(
        code=code,
        name=name,
        type=account_type,
        description=description,
        tax_type=tax_type
    )

    try:
        result = accounting_api.create_account(tenant_id, new_account)
        print(f"Account created successfully: {result.accounts[0].name} ({result.accounts[0].code})")
    except Exception as e:
        print(f"Error creating account: {e}", file=sys.stderr)
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description='Manage Xero Chart of Accounts')
    subparsers = parser.add_subparsers(dest='command', help='Command to run')

    # View command
    view_parser = subparsers.add_parser('view', help='List all accounts in CSV format')
    view_parser.add_argument('query', nargs='?', help='Filter query (e.g. "Code == \'810\'")')

    # Add command
    add_parser = subparsers.add_parser('add', help='Add a new account')
    add_parser.add_argument('--code', required=True, help='Account Code (e.g., 810)')
    add_parser.add_argument('--name', required=True, help='Account Name')
    add_parser.add_argument('--type', required=True, help='Account Type (e.g., CURRLIAB, EXPENSE, REVENUE, CURRENT)')
    add_parser.add_argument('--description', help='Account Description')
    add_parser.add_argument('--tax-type', help='Tax Type (e.g., NONE, OUTPUT, INPUT)')

    args = parser.parse_args()

    if args.command == 'view':
        api_client = get_api_client()
        tenant_id = get_tenant_id(api_client)
        list_accounts(api_client, tenant_id, args.query)
    elif args.command == 'add':
        api_client = get_api_client()
        tenant_id = get_tenant_id(api_client)
        add_account(api_client, tenant_id, args.code, args.name, args.type, args.description, args.tax_type)
    else:
        parser.print_help()

if __name__ == '__main__':
    main()
