#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "PyYAML",
#     "xero-python",
# ]
# ///
"""Xero Tenant Manager

Lists Xero tenants (organisations) available to the current OAuth token.

Usage:
    ./xero_tenant_manager.py view

Requirements:
    - xero_config.yaml (with CLIENT_ID, CLIENT_SECRET)
    - .xero_token.json (generated by xero_connect.py)
"""

import argparse
import csv
import json
import os
import signal
import sys

import yaml
from xero_python.api_client import ApiClient
from xero_python.api_client.configuration import Configuration
from xero_python.api_client.oauth2 import OAuth2Token
from xero_python.identity import IdentityApi


signal.signal(signal.SIGPIPE, signal.SIG_DFL)


def load_config(config_file: str = "xero_config.yaml") -> dict:
    if not os.path.exists(config_file):
        print(f"Config file {config_file} not found.", file=sys.stderr)
        sys.exit(1)
    with open(config_file, "r") as f:
        return yaml.safe_load(f)


def load_token(token_file: str = ".xero_token.json") -> dict:
    if not os.path.exists(token_file):
        print("Token file not found. Please run xero_connect.py first.", file=sys.stderr)
        sys.exit(1)
    with open(token_file, "r") as f:
        return json.load(f)


def get_api_client(config: dict, token_data: dict) -> ApiClient:
    oauth2_token = OAuth2Token(client_id=config["CLIENT_ID"], client_secret=config["CLIENT_SECRET"])
    oauth2_token.update_token(**token_data)

    api_client = ApiClient(Configuration(debug=False, oauth2_token=oauth2_token), pool_threads=1)

    @api_client.oauth2_token_getter
    def obtain_xero_oauth2_token():
        return token_data

    @api_client.oauth2_token_saver
    def store_xero_oauth2_token(token: dict):
        nonlocal token_data
        token_data = token
        with open(".xero_token.json", "w") as f:
            json.dump(token, f, indent=4)

    try:
        api_client.refresh_oauth2_token()
    except Exception as e:
        print(f"Warning: Token refresh failed: {e}", file=sys.stderr)

    return api_client


def list_tenants(api_client: ApiClient) -> None:
    identity_api = IdentityApi(api_client)
    connections = identity_api.get_connections()

    writer = csv.writer(sys.stdout)
    writer.writerow(
        [
            "Index",
            "TenantName",
            "TenantType",
            "TenantId",
            "ConnectionId",
            "AuthEventId",
            "CreatedDateUTC",
            "UpdatedDateUTC",
        ]
    )

    for idx, conn in enumerate(connections, start=1):
        writer.writerow(
            [
                idx,
                getattr(conn, "tenant_name", ""),
                getattr(conn, "tenant_type", ""),
                getattr(conn, "tenant_id", ""),
                getattr(conn, "id", ""),
                getattr(conn, "auth_event_id", ""),
                getattr(conn, "created_date_utc", ""),
                getattr(conn, "updated_date_utc", ""),
            ]
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="List Xero tenants available to the current token")
    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    subparsers.add_parser("view", help="List connected Xero tenants in CSV format")

    args = parser.parse_args()

    if args.command != "view":
        parser.print_help()
        return

    config = load_config()
    token_data = load_token()
    api_client = get_api_client(config, token_data)

    list_tenants(api_client)


if __name__ == "__main__":
    main()
